namespace LibMeido;

public enum Mpn {
	null_mpn,
	RegFat,
	ArmL,
	Hara,
	RegMeet,
	KubiScl,
	UdeScl,
	DouPer,
	sintyou,
	koshi,
	kata,
	west,
	MuneL,
	MuneS,
	MuneTare,
	MuneUpDown,
	MuneYori,
	MuneYawaraka,
	MunePosX,
	MunePosY,
	MuneThick,
	MuneLong,
	MuneDir,
	DouThick1X,
	DouThick1Y,
	DouThick2X,
	DouThick2Y,
	DouThick3X,
	DouThick3Y,
	ShoulderThick,
	UpperArmThickX,
	UpperArmThickY,
	LowerArmThickX,
	LowerArmThickY,
	ElbowThickX,
	ElbowThickY,
	NeckThickX,
	NeckThickY,
	HandSize,
	DouThick4X,
	DouThick4Y,
	DouThick5X,
	DouThick5Y,
	WaistPos,
	HipSize,
	HipRot,
	ThighThickX,
	ThighThickY,
	KneeThickX,
	KneeThickY,
	CalfThickX,
	CalfThickY,
	AnkleThickX,
	AnkleThickY,
	FootSize,
	UpperArmLowerThickX,
	UpperArmLowerThickY,
	WristThickX,
	WristThickY,
	ClavicleThick,
	ShoulderTension,
	ThighLowerThickX,
	ThighLowerThickY,
	ThighShin,
	HaraN,
	ChikubiH,
	ChikubiK1,
	ChikubiK2,
	ChikubiK2_MuneS,
	ChikubiR,
	ChikubiW,
	Nyurin1,
	Nyurin2,
	Nyurin3,
	Nyurin4,
	Nyurin5,
	Nyurin6,
	Nyurin7,
	Nyurin8,
	ChikubiWearTotsu,
	HeadX,
	HeadY,
	FaceShape,
	FaceShapeSlim,
	EyeScl,
	EyeSclX,
	EyeSclY,
	EyePosX,
	EyePosY,
	EyeClose,
	EyeBallPosX,
	EyeBallPosY,
	EyeBallSclX,
	EyeBallSclY,
	EarNone,
	EarElf,
	EarRot,
	EarScl,
	NosePos,
	NoseScl,
	MayuShapeIn,
	MayuShapeOut,
	MayuX,
	MayuY,
	MayuRot,
	MayuThick,
	MayuLong,
	Yorime,
	MabutaUpIn,
	MabutaUpIn2,
	MabutaUpMiddle,
	MabutaUpOut,
	MabutaUpOut2,
	MabutaLowIn,
	MabutaLowUpMiddle,
	MabutaLowUpOut,
	Ha1,
	Ha2,
	Ha3,
	Ha4,
	Ha5,
	Ha6,
	FutaePosX,
	FutaePosY,
	FutaeRot,
	HitomiHiPosX,
	HitomiHiPosY,
	HitomiHiSclY,
	HitomiShapeUp,
	HitomiShapeLow,
	HitomiShapeIn,
	HitomiShapeOutUp,
	HitomiShapeOutLow,
	HitomiRot,
	HohoShape,
	LipThick,
	WearSuso,
	KuikomiPants,
	KuikomiStkg,
	body,
	moza,
	head,
	hairf,
	hairr,
	hairt,
	hairs,
	hairaho,
	haircolor,
	skin,
	acctatoo,
	accnail,
	underhair,
	asshair,
	hokuro,
	mayu,
	lip,
	chikubi,
	chikubicolor,
	eye,
	eye_hi,
	eye_hi_r,
	eyewhite,
	nose,
	facegloss,
	matsuge_up,
	matsuge_low,
	futae,
	wear,
	skirt,
	mizugi,
	mizugi_top,
	mizugi_buttom,
	bra,
	panz,
	slip,
	stkg,
	shoes,
	headset,
	glove,
	acchead,
	accha,
	acchana,
	accface,
	acckamisub,
	acckami,
	accmimi,
	accnip,
	acckubi,
	acckubiwa,
	accheso,
	accude,
	accashi,
	accsenaka,
	accshippo,
	acckoshi,
	accanl,
	accvag,
	megane,
	accxxx,
	handitem,
	acchat,
	onepiece,
	set_maidwear,
	set_mywear,
	set_underwear,
	set_body,
	set_face,
	folder_eye,
	folder_mayu,
	folder_underhair,
	folder_skin,
	folder_eyewhite,
	folder_matsuge_up,
	folder_matsuge_low,
	folder_futae,
	kousoku_upper,
	kousoku_lower,
	seieki_naka,
	seieki_hara,
	seieki_face,
	seieki_mune,
	seieki_hip,
	seieki_ude,
	seieki_ashi,
}

public enum MPN2 {
	None = Mpn.null_mpn,
	LegThickness = Mpn.RegFat,
	ArmSize = Mpn.ArmL,
	Belly = Mpn.Hara,
	LegThickness2 = Mpn.RegMeet,
	NeckLength = Mpn.KubiScl,
	ArmLength = Mpn.UdeScl,
	LegLength = Mpn.DouPer,
	Height = Mpn.sintyou,
	Hip = Mpn.koshi,
	ShoulderWidth = Mpn.kata,
	Waist = Mpn.west,
	BreastSize = Mpn.MuneL,
	MuneS = Mpn.MuneS,
	BreastSag = Mpn.MuneTare,
	NipplesPos = Mpn.MuneUpDown,
	BreastDirection = Mpn.MuneYori,
	BreastShake = Mpn.MuneYawaraka,
	//= MPN.MunePosX,
	//= MPN.MunePosY,
	//= MPN.MuneThick,
	//= MPN.MuneLong,
	//= MPN.MuneDir,
	//= MPN.DouThick1X,
	//= MPN.DouThick1Y,
	//= MPN.DouThick2X,
	//= MPN.DouThick2Y,
	//= MPN.DouThick3X,
	//= MPN.DouThick3Y,
	//= MPN.ShoulderThick,
	//= MPN.UpperArmThickX,
	//= MPN.UpperArmThickY,
	//= MPN.LowerArmThickX,
	//= MPN.LowerArmThickY,
	//= MPN.ElbowThickX,
	//= MPN.ElbowThickY,
	//= MPN.NeckThickX,
	//= MPN.NeckThickY,
	//= MPN.HandSize,
	//= MPN.DouThick4X,
	//= MPN.DouThick4Y,
	//= MPN.DouThick5X,
	//= MPN.DouThick5Y,
	//= MPN.WaistPos,
	//= MPN.HipSize,
	//= MPN.HipRot,
	//= MPN.ThighThickX,
	//= MPN.ThighThickY,
	//= MPN.KneeThickX,
	//= MPN.KneeThickY,
	//= MPN.CalfThickX,
	//= MPN.CalfThickY,
	//= MPN.AnkleThickX,
	//= MPN.AnkleThickY,
	//= MPN.FootSize,
	//= MPN.UpperArmLowerThickX,
	//= MPN.UpperArmLowerThickY,
	//= MPN.WristThickX,
	//= MPN.WristThickY,
	//= MPN.ClavicleThick,
	//= MPN.ShoulderTension,
	//= MPN.ThighLowerThickX,
	//= MPN.ThighLowerThickY,
	//= MPN.ThighShin,
	//= MPN.HaraN,
	//= MPN.ChikubiH,
	//= MPN.ChikubiK1,
	//= MPN.ChikubiK2,
	//= MPN.ChikubiK2_MuneS,
	//= MPN.ChikubiR,
	//= MPN.ChikubiW,
	//= MPN.Nyurin1,
	//= MPN.Nyurin2,
	//= MPN.Nyurin3,
	//= MPN.Nyurin4,
	//= MPN.Nyurin5,
	//= MPN.Nyurin6,
	//= MPN.Nyurin7,
	//= MPN.Nyurin8,
	//= MPN.ChikubiWearTotsu,
	HeadWidth = Mpn.HeadX,
	HeadHeight = Mpn.HeadY,
	FaceRound = Mpn.FaceShape,
	FacePointed = Mpn.FaceShapeSlim,
	EyesScale = Mpn.EyeScl,
	EyesWidth = Mpn.EyeSclX,
	EyesHeight = Mpn.EyeSclY,
	EyesPosX = Mpn.EyePosX,
	EyesPosY = Mpn.EyePosY,
	EyesClose = Mpn.EyeClose,
	EyeBallPosX = Mpn.EyeBallPosX, // MPN.Yorime ??
	EyeBallPosY = Mpn.EyeBallPosY,
	EyeBallSclX = Mpn.EyeBallSclX,
	EyeBallSclY = Mpn.EyeBallSclY,
	EarNone = Mpn.EarNone,
	EarElf = Mpn.EarElf,
	EarRot = Mpn.EarRot,
	EarScl = Mpn.EarScl,
	NosePos = Mpn.NosePos,
	NoseScl = Mpn.NoseScl,
	EyebrowsShapeIn = Mpn.MayuShapeIn,
	EyebrowsShapeOut = Mpn.MayuShapeOut,
	EyebrowsPosX = Mpn.MayuX,
	EyebrowsPosY = Mpn.MayuY,
	EyebrowsAngle = Mpn.MayuRot,
	EyebrowsThickness = Mpn.MayuThick,
	EyebrowsLength = Mpn.MayuLong,
	EyeBallPosX2 = Mpn.Yorime, // ??
	EyelidUpperIn = Mpn.MabutaUpIn,
	EyelidUpperInMid = Mpn.MabutaUpIn2,
	EyelidUpperMid = Mpn.MabutaUpMiddle,
	EyelidUpperOutMid = Mpn.MabutaUpOut,
	EyelidUpperOut = Mpn.MabutaUpOut2,
	EyelidLowerIn = Mpn.MabutaLowIn,
	EyelidLowerMid = Mpn.MabutaLowUpMiddle,
	EyelidLowerOut = Mpn.MabutaLowUpOut,
	//= MPN.Ha1,
	//= MPN.Ha2,
	//= MPN.Ha3,
	//= MPN.Ha4,
	//= MPN.Ha5,
	//= MPN.Ha6,
	//= MPN.FutaePosX,
	//= MPN.FutaePosY,
	//= MPN.FutaeRot,
	//= MPN.HitomiHiPosX,
	//= MPN.HitomiHiPosY,
	//= MPN.HitomiHiSclY,
	//= MPN.HitomiShapeUp,
	//= MPN.HitomiShapeLow,
	//= MPN.HitomiShapeIn,
	//= MPN.HitomiShapeOutUp,
	//= MPN.HitomiShapeOutLow,
	//= MPN.HitomiRot,
	//= MPN.HohoShape,
	//= MPN.LipThick,
	//= MPN.WearSuso,
	//= MPN.KuikomiPants,
	//= MPN.KuikomiStkg,
	Body = Mpn.body,
	Mozaic = Mpn.moza,
	Face = Mpn.head,
	HairFront = Mpn.hairf,
	HairBack = Mpn.hairr,
	HairExtensions = Mpn.hairt,
	HairSide = Mpn.hairs,
	HairAhoge = Mpn.hairaho,
	HairColor = Mpn.haircolor,
	SkinColor = Mpn.skin,
	Tattoo = Mpn.acctatoo,
	Nail = Mpn.accnail,
	GenitalHairColor = Mpn.underhair,
	//= MPN.asshair,
	BeautyMark = Mpn.hokuro,
	EyebrowsColor = Mpn.mayu,
	Lips = Mpn.lip,
	Nipples = Mpn.chikubi,
	NipplesColor = Mpn.chikubicolor,
	EyesColor = Mpn.eye,
	EyeHighlights = Mpn.eye_hi,
	EyeHighlightsRight = Mpn.eye_hi_r,
	WhiteOfEyeColor = Mpn.eyewhite,
	Nose = Mpn.nose,
	CheekTint = Mpn.facegloss,
	EyelashesTopColor = Mpn.matsuge_up,
	EyelashesBottomColor = Mpn.matsuge_low,
	DoubleEyelidColor = Mpn.futae,
	Top = Mpn.wear,
	Bottom = Mpn.skirt,
	Swimsuit = Mpn.mizugi,
	SwimsuitTop = Mpn.mizugi_top,
	SwimsuitBottom = Mpn.mizugi_buttom,
	Bra = Mpn.bra,
	Panties = Mpn.panz,
	//= MPN.slip,
	Socks = Mpn.stkg,
	Shoes = Mpn.shoes,
	HeadDress = Mpn.headset,
	Gloves = Mpn.glove,
	EyeMask = Mpn.acchead,
	Teeth = Mpn.accha,
	NosePiercing = Mpn.acchana,
	//= MPN.accface,
	Ribbon = Mpn.acckamisub,
	HairClip = Mpn.acckami,
	EarRing = Mpn.accmimi,
	NipplePiercing = Mpn.accnip,
	Necklace = Mpn.acckubi,
	Choker = Mpn.acckubiwa,
	BellyButtonPiercing = Mpn.accheso,
	Arm = Mpn.accude,
	Ankle = Mpn.accashi,
	Back = Mpn.accsenaka,
	Tail = Mpn.accshippo,
	//= MPN.acckoshi,
	AccAnl = Mpn.accanl,
	AccVag = Mpn.accvag,
	Glasses = Mpn.megane,
	VaginaPiercing = Mpn.accxxx,
	HandItem = Mpn.handitem,
	Hat = Mpn.acchat,
	OnePiece = Mpn.onepiece,
	SetMaidWear = Mpn.set_maidwear,
	SetMyWear = Mpn.set_mywear,
	SetUnderwear = Mpn.set_underwear,
	SetBody = Mpn.set_body,
	SetFace = Mpn.set_face,
	Eyes = Mpn.folder_eye,
	Eyebrows = Mpn.folder_mayu,
	GenitalHair = Mpn.folder_underhair,
	Skin = Mpn.folder_skin,
	WhiteOfTheEye = Mpn.folder_eyewhite,
	EyelashTop = Mpn.folder_matsuge_up,
	EyelashBottom = Mpn.folder_matsuge_low,
	DoubleEyelids = Mpn.folder_futae,
	kousoku_upper = Mpn.kousoku_upper,
	kousoku_lower = Mpn.kousoku_lower,
	SemenNaka = Mpn.seieki_naka,
	SemenBelly = Mpn.seieki_hara,
	SemenFace = Mpn.seieki_face,
	SemenBreast = Mpn.seieki_mune,
	SemenHip = Mpn.seieki_hip,
	SemenArm = Mpn.seieki_ude,
	SemenAnkle = Mpn.seieki_ashi,
}
