name: build

on:
  push:
    tags:
      - '**'

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  OUTPUT_NAME: LibMeido

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        dotnet-quality: ga

    - name: Install dependencies
      run: dotnet restore LibMeido
      
    - name: Build
      run: dotnet build LibMeido --configuration Release --no-restore
      
    - name: Create the package
      run: |
        $archiveName = "$env:OUTPUT_NAME-$env:GITHUB_REF_NAME.zip"
        Add-Content -Value "ARCHIVE_NAME=$archiveName" -Path $env:GITHUB_ENV
        Compress-Archive -Path LibMeido\bin\Release\net35\$env:OUTPUT_NAME.dll, LibMeido\bin\Release\net35\CM3D2.Toolkit.Guest4168Branch.dll -DestinationPath $archiveName -CompressionLevel NoCompression

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        prerelease: true
        files: ${{ env.ARCHIVE_NAME }}
